// =============================================
// LOGIN
// =============================================
async function handleLogin() {
    const user     = (document.getElementById('username').value || '').trim().toUpperCase();
    const pass     = document.getElementById('password').value || '';
    const errorMsg = document.getElementById('login-error');
    const btn      = document.getElementById('loginBtn');

    errorMsg.classList.add('hidden');

    if (!user || !pass) {
        errorMsg.innerText = 'CREDENTIALS REQUIRED';
        errorMsg.classList.remove('hidden');
        return;
    }

    btn.innerHTML = '<div class="spinner" style="width:14px;height:14px;border-width:2px;border-top-color:#ffffff;border-color:rgba(255,255,255,0.3);"></div> LOGGING IN...';
    btn.disabled  = true;

    try {
        const { data, error } = await db
            .from('users')
            .select('*')
            .eq('username', user)
            .eq('password', pass)
            .eq('status', 'ACTIVE')
            .single();

        if (error || !data) throw new Error('Invalid Credentials');

        // Determine role from DB record strictly
        const dbRole       = (data.role || '').toUpperCase();
        const resolvedRole = dbRole === 'ADMIN' ? 'ADMIN' : 'ENCODER';

        // ✅ Write ALL session values to localStorage FIRST — before any access check
        localStorage.setItem('isLoggedIn',     'true');
        localStorage.setItem('loginTimestamp', Date.now());
        localStorage.setItem('username',       data.username);
        localStorage.setItem('branch',         data.branch || '');
        localStorage.setItem('userRole',       resolvedRole);
        sessionStorage.setItem('isLoggedIn',   'true');

        showDashboard();
        checkAdminAccess();   // now runs with role already in localStorage
        initializeAppData();
        setTimeout(startRealtimeSync, 800);

        // Write USER_LOGIN to Supabase (once, on actual login)
        // Only send the 3 writable columns — id and created_at are auto-generated by Supabase
        try {
            const { error: loginLogErr } = await db.from('audit_logs').insert([{
                actor:   data.username,
                action:  'USER_LOGIN',
                details: `User "${data.username}" logged in successfully (role: ${resolvedRole})`
            }]);
            if (loginLogErr) console.error('[AuditLog] USER_LOGIN write failed:', loginLogErr.message);
        } catch(e) { console.error('[AuditLog] USER_LOGIN exception:', e.message); }

        setTimeout(() => pushNotif('🔐 Logged in as ' + data.username, 'info'), 1500);

    } catch (err) {
        const msg = err.message === 'Invalid Credentials' ? 'INVALID CREDENTIALS' : 'CONNECTION ERROR — RETRY';
        errorMsg.innerText = msg;
        errorMsg.classList.remove('hidden');
        btn.innerHTML = '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/><polyline points="10 17 15 12 10 7"/><line x1="15" y1="12" x2="3" y2="12"/></svg> SIGN IN';
        btn.disabled  = false;
    }
}
